### ISSUE TITLE
Remove linked dependency from examples

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-sdk#130]
All of our current examples use `sdk` as linked dependency and not from npm registry. This add complexity when trying to run examples and its less straightfoward since it need to run TS compiler in the sdk folder.

## Implementation details

Remove examples folder from workspaces to use dependency from npm.

**Comment by BeroBurny** [comment]
Wound recommends doing that way explained in "Implementation details" as the project uses yarn workspaces and there is a feature that provides a perfect option for this case.
You can change `link` approach (that is pretty outdated) in favor of the [`workspace:^`](https://classic.yarnpkg.com/en/package/@yarnpkg/plugin-workspace-tools) example in [`filesnap`](https://github.com/ChainSafe/filsnap/blob/2d530641866bdc067087f5964a61b61f5d327e61/packages/example/package.json#L11)
