### ISSUE TITLE
Broken `sygma-sdk-erc20-react-example`

### ISSUE THREAD

**Issue by BeroBurny** [sygmaprotocol/sygma-sdk#151]
## Expected Behavior
When running example following instructions to work 

## Current Behavior
You can run the example without a problem but is UI is broken
![image](https://user-images.githubusercontent.com/6376047/214038905-cb59ee59-2388-4aee-8fb7-9f251022ea6b.png)

## Steps to Reproduce (for bugs)
1. Clone project
2. build SDK
3. run the relayer
4. follow instructions to run an example
5. press connect button on the UI

## Versions
main

**Comment by enemycnt** [comment]
Close in favor #199
