### ISSUE TITLE
Broken `sygma-sdk-erc721-react-example`

### ISSUE THREAD

**Issue by BeroBurny** [sygmaprotocol/sygma-sdk#152]
## Expected Behavior
When running example following instructions to work 

## Current Behavior
You can run the example without a problem but is UI is broken
![image](https://user-images.githubusercontent.com/6376047/214041479-e82c1f49-3272-4c22-ba55-d1a34ff21a95.png)

## Steps to Reproduce (for bugs)
1. Clone project
2. build SDK
3. run the relayer
4. follow instructions to run an example
5. press connect button on the UI

## Versions
main

**Comment by mpetrun5** [comment]
The example is removed until the SDK upgrade.
Will be revisited for: #241
