### ISSUE TITLE
Update `sygma-sdk-erc20-react-example`

### ISSUE THREAD

**Issue by enemycnt** [sygmaprotocol/sygma-sdk#199]
The task involves fixing the `sygma-sdk-erc20-react-example`. The application needs to be migrated from its current build tool to Vite, a build tool that provides faster build times and other benefits. Additionally, the configuration files need to be extracted to a separate config file, the README needs to be updated, and an end-to-end (E2E) test using Cypress needs to be added.

### Implementation Details
- Migrate the `sygma-sdk-erc20-react-example` from CRA to Vite
- Extract the configuration files to a separate config file to make it easier to manage and maintain the code
- Update the readme file to include instructions on how to run the application, how to build it, and any other relevant information
- Add an end-to-end (E2E) test using Cypress to ensure that the application is working as expected
- The E2E test should be executed **locally**. Integrating the E2E into the CI system will be created as a separate task due to its complexity.

### Testing Details
- Test the application to ensure that the migration to Vite has not caused any issues
- Test the configuration files to ensure that they are correctly extracted and that they are working as expected
- Test the E2E test using Cypress to ensure that it is working as expected

### Acceptance Criteria
The acceptance criteria for this task include the following conditions of satisfaction:
- The `sygma-sdk-erc20-react-example` has been successfully migrated to Vite, and the application is running smoothly
- The configuration files have been successfully extracted to a separate config file, and they are working as expected
- The readme file has been updated with instructions on how to run the application, how to build it, and any other relevant information
- The end-to-end (E2E) test using Cypress has been added and is working as expected

**Comment by mpetrun5** [comment]
The examples will be revisited after the SDK upgrade
