### ISSUE TITLE
Update ethersjs from v5 to v6

### ISSUE THREAD

**Issue by enemycnt** [sygmaprotocol/sygma-sdk#230]
## Implementation Details
Upgrade the ethersjs library in the project from version 5 to version 6, ensuring all dependencies are properly updated and any breaking changes are addressed.

## Testing Details
1. Test existing functionality to ensure there are no regressions caused by the update.
2. Test any new features or improvements introduced in ethersjs v6, verifying they work as expected.
3. Ensure all unit tests pass after the update.

## Acceptance Criteria
- Successfully upgraded to ethersjs v6 without any loss of existing functionality.
- All new features and improvements in ethersjs v6 are integrated and working as expected.
- All unit tests pass after the update.

**Comment by MakMuftic** [comment]
Not relevant anymore.
