### ISSUE TITLE
Rename FeeDataResult to EvmFee and create SubstrateFee

### ISSUE THREAD

**Issue by enemycnt** [sygmaprotocol/sygma-sdk#231]
## Implementation Details
1. Rename the current type `FeeDataResult` to `EvmFee` in the codebase.
2. Create a new type called `SubstrateFee` for Substrate-specific fee data.
3. Update all references and usages of the old type to the new type names.

## Testing Details
- Test existing functionality to ensure renaming has not caused any issues.

## Acceptance Criteria
- The type `FeeDataResult` has been successfully renamed to `EvmFee`.
- The new `SubstrateFee` type is created and integrated into the codebase.
- All references and usages of the old and new types are updated accordingly.

**Comment by mpetrun5** [comment]
Superseeded by: #237 and #238
