### ISSUE TITLE
Improve Error Handling with `Either`

### ISSUE THREAD

**Issue by enemycnt** [sygmaprotocol/sygma-sdk#232]
## Implementation Details
1. Replace current error handling using `Promise.rejects(error)` with the Either pattern for better error handling and control flow.
2. Refactor affected functions to return Either objects (Left for errors and Right for successful results).
3. Update relevant parts of the codebase to handle the new Either-based error handling.

## Testing Details
1. Test existing functionality to ensure the new error handling approach has not caused any issues.
2. Test error scenarios to verify the correct error handling and messages are provided using the Either pattern.

## Acceptance Criteria
- The error handling using `Promise.rejects(error)` is successfully replaced with the Either pattern.
- Affected functions return Either objects (Left for errors and Right for successful results).
- The codebase is updated to handle the new Either-based error handling approach.

**Comment by mpetrun5** [comment]
Decided against it for now and will just throw errors.
