### ISSUE TITLE
Update EVM to Substrate example with feeRouter logic 

### ISSUE THREAD

**Issue by enemycnt** [sygmaprotocol/sygma-sdk#234]
Replace the direct use of fee handler with feeRouter logic in the EVM to Substrate example.

### Implementation Details
- Update the EVM to Substrate example by integrating the feeRouter logic.
- Remove the direct usage of the fee handler in the example.
- Ensure that the new implementation is compatible with existing components and follows best practices.

### Testing Details
- Test the updated example with various scenarios to ensure that the feeRouter logic is working correctly.
- Verify that the removal of the direct fee handler usage does not introduce any issues or conflicts.

### Acceptance Criteria
- The EVM to Substrate example is successfully updated with the feeRouter logic.
- The updated implementation is tested and verified to be working correctly.

**Comment by mpetrun5** [comment]
Will be revisited with: #241
