### ISSUE TITLE
Standardize transfer amount on evm and substrate

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-sdk#272]
Currently `EvmAssetTransfer` and `SubstrateAssetTransfer` use different approach when interpreting amount defined inside `Transfer`. You can see this in action [inside local-example](https://github.com/sygmaprotocol/sygma-sdk/blob/main/examples/local-fungible-transfer/src/transfer.ts).

## Implementation details

TBD

## Testing details

TBD

## Acceptance Criteria

- [ ] Both `EvmAssetTransfer` and `SubstrateAssetTransfer` use same approach when interpreting transfer amount
- [ ] All examples updated to reflect this

**Comment by itsbobbyzzz168** [comment]
@FSM1 

Just FYI on Dotasama's existential deposit - https://support.polkadot.network/support/solutions/articles/65000168651-what-is-the-existential-deposit-#:~:text=Print&text=On%20most%20Substrate%2Dbased%20chains,the%20Existential%20Deposit%20(ED).

On most Substrate-based chains, an account is only active when it holds a minimum amount, currently set at 1 DOT on Polkadot and 0.000333333 KSM on Kusama. This minimum amount is called the Existential Deposit (ED).

Also to note as we discussed, each parachain can have differing decimal places for their native token - some are 10 and some are 12.

**Comment by itsbobbyzzz168** [comment]
also https://www.fyeo.io/post/substrate-polkadot-parachains-security-and-mitigation
