### ISSUE TITLE
Create methods to get info about the supported domains

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-sdk#306]
Curently SDK uses internally `Config` class to access info about supported networks and assets. For widget and other purposes we would need to access that info without instantiating the config class that's is already being used by the SDK

## Implementation details

- create methods to get supported networks
- there are some methods already implemented by the `Config` class, expose them on the SDK level

## Acceptance Criteria

- we are able to get information about current supported domains

**Comment by MakMuftic** [comment]
Not relevant
