### ISSUE TITLE
Support multiple environments

### ISSUE THREAD

**Issue by mpetrun5** [sygmaprotocol/sygma-sdk#331]
Currently, we only support V1 (MPC) environment and the config and transfer classes expect to use that environment.
We want to be able to choose (depending on a transfer param) which configuration is used (V1 - MPC, V2 - Sygma X).

## Implementation details

The shared configuration outline is still TBD, but should be largely the same except `bridge` is separate into `router` and `executor`.

## Testing details

 - unit tests

## Acceptance Criteria

 - transfer classes support using custom configurations

**Comment by saadahmsiddiqui** [comment]
Not relevant anymore with new version of the SDK so I am closing this issue
Feel free to re open if you encounter any issue
