### ISSUE TITLE
While using the SDK examples the RPC response sending the TX on chain, generates a parsing error message

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-sdk#337]
**Context**: Using the https://github.com/sygmaprotocol/sygma-sdk/blob/main/examples/evm-to-evm-fungible-transfer/src/transfer.ts  examples to send a bridge request, there are responses from the RPC that display error error messages. 

**STR**
1.  Set the transfer.ts file to send 5 sygUSDC from Goerli to Sepolia. 
2.  Run the script. 

**Exp**: The allowance and deposit tx to be propagated and keep an open listening for execution on destination. 
**Act**: The allowance and deposit tx to be propagated, and an open listening is active until execution on destination is complete, but constantly displaying an RPC error message. 
![image](https://github.com/sygmaprotocol/sygma-sdk/assets/30255634/90ae53d3-b65b-4a8d-ba1b-99e1650a943f)

**Comment by saadjhk** [comment]
Closing as this doesn't apply to newer version
