### ISSUE TITLE
Using the SDK when trying to send a value higher than the balance is allowed

### ISSUE THREAD

**Issue by LyonSsS** [sygmaprotocol/sygma-sdk#338]
**Context**: While using the SDK https://github.com/sygmaprotocol/sygma-sdk/blob/main/examples/evm-to-evm-fungible-transfer/src/transfer.ts to transfer Fungible token EVM to EVM, of a token that is also the FEE, for a value that is > actual balance, it is allowed.

**STR**:
1. Have a wallet on source with 1000 sygUSDC.
2. Use the SDK to transfer 1500 sygUSDC to another compatible destination.

**Expectancy**: 
The TX should be discarded from the beginning as the the transfer value of 1500 is higher than the actual balance.

**Actual**:
The TX is emitted and fails after partial execution.
https://sepolia.etherscan.io/tx/0x25a6b39ae8ac84b945c3695212199f37c602ebf37d48ca1bf26bbfca84ac16cd

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/338?planning-poker) with Zenhub @saadjhk @wainola @Lykhoyda
