### ISSUE TITLE
SDK example not working

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-sdk#355]
With Goerli domain officially deprecated from the shared config, all sygma-sdk examples are now broken.

## Implementation details

Refactor examples to use active routes.

## Testing details

- [ ] Manually execute all examples

## Acceptance Criteria

- [ ] All examples successfully execute on testnet

**Comment by LyonSsS** [comment]
Tested and closed on https://github.com/sygmaprotocol/sygma-sdk/pull/356
