### ISSUE TITLE
SDK should fetch feeRouter and feeHandler onchain

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-sdk#363]
## Implementation details

SDK should obtain bridge address from shared config and use that to fetch fee related contracts and information instead of depending on shared config to avoid errors when shared config is different from onchain status.

**Comment by saadjhk** [comment]
Closed in v3 refactor
https://github.com/sygmaprotocol/sygma-sdk/blob/v3/packages/evm/src/fee/getFeeInformation.ts#L20
