### ISSUE TITLE
Implement fungible EVM transfers

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-sdk#371]
Following the [proposed `v3` SDK restructure](https://github.com/sygmaprotocol/sygma-sdk/tree/v3), implement/restructure the necessary functions for creating deposit EVM transactions for fungible assets (ERC20).

## Implementation details

- Check `packages/evm/src/fungible.ts` for the interface definitions.
- Make sure to also tackle bug #363 with this refactor 
## Testing details

- Restructure and update existing unit tests (expand if required)
- Validate manually that refactored `evm-to-evm-fungible-transfer-example` is passing on testnet

## QA Details

- New exposed interfaces and functions should allow the same functionalities as the v2 SDK implementation, such as the creation of fungible EVM transfers and the estimation of fees.

## Acceptance Criteria
- [ ] Implementing fungible EVM transfers following `v3` guidlines
- [ ] Restructure and update existing unit tests
- [ ] Update `evm-to-evm-fungible-transfer-example` example to use `v3` implementation
- [ ] Validate `evm-to-evm-fungible-transfer-example` example manually on testnet

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/371?planning-poker) with Zenhub @Lykhoyda @mpetrunic @saadjhk @wainola

**Comment by LyonSsS** [comment]
Tested in relationship with https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/project-backlog/253 
Tests done: Implement fungible EVM transfers topic ->  https://docs.google.com/spreadsheets/d/13SRvdjjrnSIjhD26eFG3xV0pcGsBtq9SV1Dc_lUkACM/edit?pli=1&gid=2049882071#gid=2049882071   
QA ready
