### ISSUE TITLE
Implement fungible Substrate transfer

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-sdk#372]
Following the [proposed `v3` SDK restructure](https://github.com/sygmaprotocol/sygma-sdk/tree/v3), implement/restructure the necessary functions for creating deposit Substrate transactions for fungible assets.

## Implementation details

Check `packages/substrate/src/fungible.ts` for the interface definitions.

## Testing details

- Restructure and update existing unit tests (expand if required)
- Validate manually that refactored `substrate-to-evm-fungible-transfer-example` is passing on testnet

## QA Details

- New exposed interfaces and functions should allow the same functionalities as the v2 SDK implementation, such as the creation of fungible Substrate transfers and the estimation of fees.

## Acceptance Criteria
- [ ] Implementing fungible Substrate transfers following `v3` guidlines
- [ ] Restructure and update existing unit tests
- [ ] Update `substrate-to-evm-fungible-transfer-example` example to use `v3` implementation
- [ ] Validate `substrate-to-evm-fungible-transfer-example` example manually on testnet

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/372?planning-poker) with Zenhub @Lykhoyda @mpetrunic @saadjhk @wainola

**Comment by saadjhk** [comment]
Marking this as closed as #378 is merged

**Comment by LyonSsS** [comment]
QA tests: The resourceID from the sourceID chain is not correct mapped to the shared config. 
Tested from Tangle to Sepolia 
`const DEST_EVM_CHAIN_ID = 11155111;
const SOURCE_SUBSTRATE_CHAIN_ID = 5231;

const RESOURCE_ID_SYGMA_USD =
  "0x0000000000000000000000000000000000000000000000000000000000001000";
const recipient = "0x9A17FA0A2824EA855EC6aD3eAb3Aa2516EC6626d";
const SOURCE_CHAIN_RPC_URL =
  process.env.RHALA_RPC_URL ?? "wss://testnet-rpc.tangle.tools";`

and for resourceID: 0x0000000000000000000000000000000000000000000000000000000000001000 it did transfered tTNT token. In reality the _1000 ressID is for the PHA token 
<img width="806" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3255d7e605cfb9fb05673d4b68aa85e1dc9344b2/image.png" alt="image.png" />

Now using the other resourceIDs I get some error which I suspect they may be from this ressID mapping issue.

**Comment by LyonSsS** [comment]
It might be that there was an issue with the shared config - mismatching ressourceID. 
Retested on tangle after Tangle update and Sepolia Resource ID dest update and workd fine for tTNT 
tTNT execution hash `0xf9028400cec3f9df482b8de041a81dae22a494a3446966fcf1fab4afbf4fc00028e9142401c657cbf8730caab483e3826770323d0d8dba257249198419b1038afc244bb1783e154d58e47a1d44368cd8ecf412881a830a216148f046aa8605488f3999578555008c00003105000000130000d52ae311ea02000306057379676d610000000000000000000000000000000000000000000000000000000508061498729c03c4d5e820f5e8c45558ae07ae63f97461000000000000000000000000`

<img width="874" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae0a431d19aa145b213ce5cf7795296ec2996117/image.png" alt="image.png" />

https://sepolia.etherscan.io/tx/0xaa02f242cd0ff248ac75f8ad55d144e714ec3362321c63aaaa8ecb4b83c10343

**Comment by LyonSsS** [comment]
Retested with the new Tangle added - > works fine - only testable with tTNT atm. 
https://docs.google.com/spreadsheets/d/13SRvdjjrnSIjhD26eFG3xV0pcGsBtq9SV1Dc_lUkACM/edit?pli=1&gid=2049882071#gid=2049882071
