### ISSUE TITLE
Implement generic EVM messages

### ISSUE THREAD

**Issue by MakMuftic** [sygmaprotocol/sygma-sdk#373]
Following the [proposed `v3` SDK restructure](https://github.com/sygmaprotocol/sygma-sdk/tree/v3), implement/restructure the necessary functions for creating GMP (General Message Passing) deposit transactions on EVM networks.

## Implementation details

Check `packages/evm/src/generic.ts` for the interface definitions.

## Testing details

- Restructure and update existing unit tests (expand if required)
- Validate manually that refactored `evm-to-evm-generic-message-example` is passing on testnet

## QA Details

- New exposed interfaces and functions should allow the same functionalities as the v2 SDK implementation, such as creating GMP transfers and estimating fees.

## Acceptance Criteria
- [ ] Implementing EVM GMP transfers following `v3` guidlines
- [ ] Restructure and update existing unit tests
- [ ] Update `evm-to-evm-generic-message-example` example to use `v3` implementation
- [ ] Validate `evm-to-evm-generic-message-example` example manually on testnet

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/373?planning-poker) with Zenhub @Lykhoyda @mpetrunic @saadjhk @wainola

**Comment by saadjhk** [comment]
@MakMuftic just to be clear, for generic messages we only support EVM to EVM right?

**Comment by haochizzle** [comment]
FWIW i think it would be highly useful to have an evm to substrate (and vice versa) example for gmp. 

further to that, @alexmmueller created a gmp usability issue for [#125](https://github.com/sygmaprotocol/docs/issues/125)

**Comment by saadjhk** [comment]
@LyonSsS GMP is now merged to SDK v3 branch you can commence testing

**Comment by LyonSsS** [comment]
Currently blocked by https://github.com/sygmaprotocol/sygma-sdk/pull/415/files
