### ISSUE TITLE
Liquidity helper in SDK v3

### ISSUE THREAD

**Issue by saadjhk** [sygmaprotocol/sygma-sdk#383]
When transferring fungible assets, its important to know whether liquidity is available on destination chain. Therefore, v3 SDK should provide interface to be able to query liquidity on destination chain and it should throw and error if there isn't enough liquidity.

## Implementation details
- Interface for querying liquidity, fungible transfer passed as parameter
- Destination provider should also be provided or created on demand by the SDK to query balances

## Testing details
- Units tests for error and success cases

## Acceptance Criteria
- A clean tested interface to query liquidity on destination chain for a specific 'transfer' object

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/383?planning-poker) with Zenhub @saadjhk @wainola @Lykhoyda
