### ISSUE TITLE
Test improvements

### ISSUE THREAD

**Issue by wainola** [sygmaprotocol/sygma-sdk#390]
This is a nice to have. Currently in some of our test for substrate we have a lot of repetitive code mocking the ApiPromise instance. It could be good for readability purposes to have a global mocked instance of ApiPromise to which we pass the parameters from the test.

## Implementation details

Improve code on current test:
- mock ApiPromise as module to avoid repeating into the test

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/390?planning-poker) with Zenhub @saadjhk @wainola @Lykhoyda

**Comment by wainola** [comment]
@MakMuftic I would like to close this in favour of #410, wdyt?

**Comment by MakMuftic** [comment]
We created separate issues per network type
