### ISSUE TITLE
Add v3 tests for Fungible Token transfer classes

### ISSUE THREAD

**Issue by saadjhk** [sygmaprotocol/sygma-sdk#393]
## Implementation details
Add v3 tests for Fungible Token transfer classes

## Testing details
- Test cases with EVM and Substrate destinations
- Environment correctness
- Test validity errors
- Test transactions building process

## Acceptance Criteria
- 100% coverage of classes with most edge cases covered

**Comment by saadjhk** [comment]
@wainola I have created the issue here

**Comment by MakMuftic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sygma-Protocol-62f126a54b7d5a55203732f0/issues/sygmaprotocol/sygma-sdk/393?planning-poker) with Zenhub @saadjhk @wainola @Lykhoyda

**Comment by wainola** [comment]
@MakMuftic can we split this issue per package/network supported? ie: Evm Fungible token transfer class test, etc

**Comment by saadjhk** [comment]
@wainola that is correct, we need to write tests for each package separately so we need to divide this into smaller sub tasks

**Comment by wainola** [comment]
@MakMuftic do we close this one in favour of the others?
