### ISSUE TITLE
Add general substrate chain support and add Phala sygma pallet support

### ISSUE THREAD

**Issue by freddyli7** [sygmaprotocol/sygma-sdk#88]
SDK needs to provide Substrate as destination chain to allow other surroundings features such as Substrate fee calculation and resourceID binding, etc. when bridging from EVM to Substrate, SDK also needs to communicate with Substrate in order to send extrinsic and make a runtime call when bridging from Substrate to EVM, so general chain support is necessary.
Phala Sygma pallet will be the actual implementation after general support added 

## Implementation details

details could be found in the SoW research doc

## Testing details

Unit test

## Acceptance Criteria

SDK should have general substrate chain support including configuration structure define, communication setup

**Comment by enemycnt** [comment]
Closed in favor of separate issues, created mainly by Freddy
