### ISSUE TITLE
Implements an API call to fee oracle to fetch the Substrate related fee information

### ISSUE THREAD

**Issue by freddyli7** [sygmaprotocol/sygma-sdk#90]
## Implementation details

 details could be found in the SoW research doc

## Testing details

Unit test

## Acceptance Criteria

SDK should be able to call fee oracle api to fetch substrate fee related data

**Comment by MakMuftic** [comment]
This issue is being closed as it is being replaced by [#158](https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/sygma-sdk/158) .
