### ISSUE TITLE
Implements the logic to construct the feeData for Substrate chain

### ISSUE THREAD

**Issue by freddyli7** [sygmaprotocol/sygma-sdk#91]
feeData will be different for substrate chain comparing to evm chain, so SDK will have to construct feeData differently and send to contract for fee calculation

## Implementation details

 details could be found in the SoW research doc

## Testing details

Unit test

## Acceptance Criteria

SDK should be able to construct all necessary params that fetched from fee oracle into feeData for substrate chain

**Comment by MakMuftic** [comment]
This is deprecated, as SDK is not going to construct this data.

**Comment by MakMuftic** [comment]
This is deprecated as SDK is not going to construct this data.
